### ISSUE TITLE
As a user I would like to report an Incident

### ISSUE THREAD

**Issue by sohilpandya** [berkeley-homes/near-miss-positive-intervention#1]
As a user, I would like to report an Incident so that I can be of help to my colleagues

- [x] Report can be a near miss
- [x] Report can be a positive intervention
- [x] User can enter a name (optional)
- [x] User can select a location
- [x] User can enter a description
- [x] User can upload a photo (related #19)

**Comment by sohilpandya** [comment]
Closing the issue and clearing the backlog
